### ISSUE TITLE
O_TMPFILE not supported in docker container

### ISSUE THREAD

**Issue by jeffdaily** [ROCm/rocr_debug_agent#5]
Would it be possible to replace the use of O_TMPFILE with something else?  Using rocr_debug_agent inside a docker container does not allow O_TMPFILE.  Replacing this with mkstemp is usable within a docker container.

https://github.com/ROCm-Developer-Tools/rocr_debug_agent/blob/5bba38fbc1b67150acbf1a1e804d040b5335546a/src/code_object.cpp#L252

Perhaps the following diff?

```diff
diff --git a/src/code_object.cpp b/src/code_object.cpp
index 6a1815a..c733c69 100644
--- a/src/code_object.cpp
+++ b/src/code_object.cpp
@@ -249,7 +249,8 @@ code_object_t::open ()
     {
     }

-  int fd = ::open ("/tmp", O_TMPFILE | O_RDWR, 0666);
+  char template_[] = "/tmp/fileXXXXXX";
+  int fd = ::mkstemp (template_);
   if (fd == -1)
     {
       agent_warning ("could not create a temporary file for code object");
```

**Comment by ppanchad-amd** [comment]
Internal ticket has been created to fix this issue. Thanks!

**Comment by jamesxu2** [comment]
Hi @jeffdaily , this issue appears to have been resolved by [a fix using memfd_create](https://github.com/ROCm/rocr_debug_agent/commit/c7f246aa50ea2f3a0726bbe06cb2a7f5467aa487) a few months after you posted this issue. 

I can confirm that the [rocr_debug_agent tests](https://github.com/ROCm/rocr_debug_agent?tab=readme-ov-file#test-the-rocdebug-agent-library) pass inside a Docker container on ROCm 6.1.2.
